language: node_js

node_js:
  - "node"

before_install:
  - "npm install gitbook-cli -g"

install:
  - "gitbook install"

cache:
  directories:
    - "node_modules"

script:
  - "gitbook build . docs"

after_script:
 - git add *
 - git commit -m "update"
 - git push -f "https://${GH_TOKEN}@${GH_REF}" master
